
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - INDEXER_SERVICE_URL=http://localhost:8080
        - NLP_SERVICE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    networks:
      - app-network

  nlp-service:
    build:
      context: ./nlp_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  indexer-service:
    build:
      context: ./indexer_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
